/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2018-07-22T16:48:55. Do not modify directly. */

#include "ethminer-buildinfo.h"

const struct buildinfo* ethminer_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_version = "0.16.0.dev0+commit.ae9585e7.dirty",
        .git_commit_hash = "ae9585e7fdb1fe9c477f5ac8e87022a05194d610",
        .system_name = "linux",
        .system_processor = "x86_64",
        .compiler_id = "gnu",
        .compiler_version = "5.4.0",
        .build_type = "release",
    };
    return &buildinfo;
}
