/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2018-07-22T18:50:53. Do not modify directly. */

#include "ethminer-buildinfo.h"

const struct buildinfo* ethminer_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_version = "0.16.0.dev0+commit.b8b1c934.dirty",
        .git_commit_hash = "b8b1c9342ecde81c5b3bb78822d92938ff7df5b7",
        .system_name = "linux",
        .system_processor = "x86_64",
        .compiler_id = "gnu",
        .compiler_version = "5.4.0",
        .build_type = "release",
    };
    return &buildinfo;
}
